Lcvw 16/lcvvw 32/lcvw 35 1er sprint
LCVW-Las-Chicas-Superpoderosas/Ing_Soft2023_La_Cosa pull request #33
Opened 2023-10-10 02:05 UTC by TroianoSan

[tickets1.txt](https://github.com/LCVW-Las-Chicas-Superpoderosas/Ing_Soft2023_La_Cosa/files/12851986/tickets1.txt)

Leer txt

2023-10-10 22:06 UTC, Jety16 commented
Por que 3 prs juntos?
Separar en prs individuales

2023-10-10 22:07 UTC, Jety16 commented
Por que 3 prs juntos?
Separar en prs individuales

2023-10-10 22:41 UTC, Jety16 requested changes
para correr el pre-commit

Before you can run hooks, you need to have the pre-commit package manager installed.

Using pip:

pip install pre-commit

In a python project, add the following to your requirements.txt (or requirements-dev.txt):

pre-commit


Referencia https://pre-commit.com/


Seguir el estilo de codigo que venimos usando, esto para facilitar la correccion y la implementacion de nuevos modulos a futuro.
Está bien el trabajo! Hacer esas correciones (la mayoria solucionables con el pre-commit)
verificar la logica y agregar los casos de error (porque si falla devuelve un 500 y el front no sabe que hacer no tiene handleado esos casos!)

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +from model_base import Models, ModelBase, db_session
orderan alfabeticamente los inports

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +model_base = ModelBase()
constantes con mayuscula

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        # Get id from new_card
add salto de linea  previo a coment

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +
quitar salto de linea

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +model_base = ModelBase()
quitar porque no se usa

corre el pre-commit esto te deberia de haber saltado

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        print(initial_deck)
quitar prints

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +                             if card.type not in
fix identación

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +
quitar salto de linea

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +                    bool = False
bool es palabra recervada, nombrar las variables bien

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +            n = len(get_cards)
quitar, poner len(get_cards) directamente como parametro  del range

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +                if get_cards[i].number is not None:
analizar si el numero hace falta que sea Nulleable (Optional en pony)

me parece que podriamos hacer required y nos ahorramos esta validacion

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        la_cosa_card = self.cards.select(number=0).first()
seguir los lineamientos de nombre de variables que venimos usando. 

agregar saltos de lineas

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        all_cards = {card for card in self.cards}  # Aux
porque haces esto y no directamente all_cards = self.cards?

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        random.shuffle(mazoMezclaInicial)
FIjate que podes usar para mezclar y no tenes que hacer tanta logica pesada

https://docs.ponyorm.org/api_reference.html
```

random(limit)
    Return a number of random objects from a collection.

    g = Group[101]
    g.students.random(2)
    


```

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +                mazoMezclaInicial.pop(0)
la logica está bien pero no me convence que des el primer elemento y luego lo popeas por que no directamente usas indices de la lista?

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        # Las cartas de infectado
si falta completar las cartas de infectado, agregalo

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        for card in initial_deck:
esta logica está mal podes hacer directamente self.cards = initial_deck y un commit 

fijate en lo que hice en clean game o en el give_cards_to_users

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        self.turns = json_list
no entiendo porque modificas los turnos acá, deberian ser las cartas. 
Testear bien esto...

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +    deck = Optional(str, nullable=True)
lo veo bien, no me convence esta logica ya que tenes que modificar las cosas del deck y del cards y principalmente usas el cards, por que no mejor usar directamente todo sobre self.cards y usas el discard_pile para tener ids "prohibidas" me parece que simplificaria muchisimo la logica y ademas podes hacer uso de las funciones que brinda pony orm para manejar toda la logica.
Creo que se haría mucho mas simple.

fijate si podes hacer ese cambio en un periodo de tiempo considerable sino no importa lo modifico yo a lo largo de la semana

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        # Get id from new_card
estos coments == idem para todo el code

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +        json_list = json.dumps(deck_list)
json_list no me dice nada. 
usar nombre de variables acordes a la funcionalidad

2023-10-10 22:41 UTC, Jety16 commented on app/game/models.py
> +    def initial_repartition_of_cards(self):
revisando el codigo esta funcionalidad ya se encontraba implementada
Veo que  borraste bastante logica sobre la partida.
como la seleccion del jugador que va a ser la cosa.
evitar cartas de infectado etc.

REVISAR

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        player: Player = MODELBASE.get_first_record_by_value(
por que tipar la expresion?
Bottar el tipado no hace falta y ofusca el code

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        hand = [p.card_token for p in player.cards]
no es necesario hacer esto.
Modificar el comentario que no está relacionado con lo que hace la funcionalidad

Ojo al copiar y pegar code

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        'message': f"Player hand",
Ser mas explicito.
Poner id del usuario o informacion de a quien le corresponde la mano

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +
que pasa si no tiene ninguna mano.
o si no está en ninguna partida.
Verificar casos de error
Agregar tests comprobando esos errores

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +
remoer saltos de lineas despues de definicion de bloque logico

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        player = MODELBASE.get_first_record_by_value(Player, id=id_player)
unificar el uso de identación.
Aca no haces salto de linea para los parametros y tampoco tipas el player.

ser consistente con eso porfavor

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        game = player.game
sacar, usar player.game directamente

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        # This will need an update when we add the card that makes u pick more
eso se realiza con el efecto de la carta. no va aca esa funcionalidad.
Quitar coment

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +                detail='No more cards in deck'
esto no deberia de pasar.
Dejar ahora pero haccete un ticket que sea que se pase automaticamente del graveyard al deck

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +                detail='No more cards in deck'
idea para saber eso
len(discard_pile) == len(self.cards)

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        picked_cards.append(cards.card_token)
si solo se toma una carta. no hace falta devolver una lista

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +        'message': f"Succesfully retrieved stolen cards from deck with next_card_type",
Succesfully retrieved cards from deck

unificar comillas
f-string sin formatear. quitar

CORRER EL PRE-COMMIT

2023-10-10 22:41 UTC, Jety16 commented on app/game/view.py
> +            'picked_cards': picked_cards,
como es una sola carta
{
 'card_token':
'next_card_type':
}

2023-10-10 22:41 UTC, Jety16 commented on app/main.py
> +        default=True,
dejar como estaba

2023-10-10 22:41 UTC, Jety16 commented on app/tests/test_game.py
> +    create_data_cards_given,
ordenar alfabeticamente

2023-10-10 22:41 UTC, Jety16 commented on app/tests/test_game.py
> +            self.assertEqual(response.status_code, 200)
no hace falta que este dentro del bloque with

2023-10-10 22:41 UTC, Jety16 commented on app/tests/test_game.py
> +
agregar casos de tests con request invalida.
agregar casos de tests en los que devuelva los mensajes de error correctamente

2023-10-10 22:41 UTC, Jety16 commented on app/tests/test_game.py
> +
el resto está bastante bien! 
Corregir identacion (idem para tooodo el proyecto)

2023-10-11 00:24 UTC, TroianoSan commented on app/game/models.py
> +        # Get id from new_card
Se arreglara con el precommit?, igual me fijo como esta en otros lados y lo cambio, :+1:

2023-10-11 00:25 UTC, TroianoSan commented on app/game/models.py
> +        json_list = json.dumps(deck_list)
:+1:

2023-10-11 00:25 UTC, TroianoSan commented on app/game/models.py
> +            n = len(get_cards)
:+1:

2023-10-11 00:38 UTC, TroianoSan commented on app/game/models.py
> +    def initial_repartition_of_cards(self):
No veo donde esta implementado la funcionalidad.
Esta funcion pone en game.cards las cartas pertenecientes a la partida segun la cantidad de jugadores.

Con borrar logica de la partida es que borre codigo?
Nose si pushee mal las cosas, pero en mi local tengo actualizado lo que esta en origin/main y solo le agregue mis funciones
""
IMP:
Si le falta la funcionalidad de poner quien va a ser la cosa.
""

Con respecto a evitar cartas de infectados
En assign_cards_to_game, las cartas de infectado no deberian evitarse, porque las cartas con las que se juega un 'Game', si tiene infectados.

La logica de reparticion de cartas esta en initial_repartition_of_cards y ahi si se evita repartir las cartas de infectado al principio. Siempre quedan en el deck.

2023-10-11 00:39 UTC, TroianoSan commented on app/game/models.py
> +        all_cards = {card for card in self.cards}  # Aux
no sabia que se podia hacer eso, ahora lo pruebo y cambio si se puede

2023-10-11 00:45 UTC, TroianoSan commented on app/game/models.py
> +                mazoMezclaInicial.pop(0)
Lo hice asi para simular la vida real, en la que cuando repartis una carta, no la tenes mas en el mazo.
Puede cambiarse a usar indices de lista

2023-10-11 00:47 UTC, TroianoSan commented on app/game/models.py
> +        # Las cartas de infectado
Faltaba quitar el comentario, es lo que se encontraba abajo, quito el comentario

2023-10-11 01:07 UTC, TroianoSan commented on app/game/view.py
> +        picked_cards.append(cards.card_token)
Estaba pensado para la carta que te hace agarrar mas de una carta. Pero si lo maneja el efecto de la partida, deberia proponer cambiar el endpoint(Esta en el excel como una lista)

2023-10-11 01:15 UTC, TroianoSan commented on app/game/models.py
> +    deck = Optional(str, nullable=True)
Esta es mi justificacion a porque lo implemente asi, no tengo drama si lo cambias pero me cuesta verlo como lo ves vos.

El motivo de la logica es que
Hay 3 cosas que tener en cuenta.

1.- Las cartas en el mazo
2.- Las cartas en la mano de los jugadores
3.- Las cartas en el mazo de descartes

Me parecio mas sencillo tener en 
self.cards todas las cartas del juego en general, SOLO SE MODIFICA AL COMIENZO(Las cartas que hay segun la cantidad de jugadores) Y LUEGO NO SE MODIFICA

En deck estarian las cartas que NO estan en 2.- ni en 3.-

En discard_pile estarian las cartas que NO estan en 1.- ni en 2.-

No veo como hacer lo de las ID "prohibidas", porque no quedaria "registradas"
las cartas que tiene el jugador. Me refiero

Si ponemos TODAS las id que no estan en el self.cards como prohibidas, puede ser que
no este en el deck pero tampoco este en el discard_pile, osea, esta en la mano del jugador.
Y tambien las que estan en la mano del jugador deberian ser "Prohibidas"(No se deberian poder sacar del mazo)

A mi vista:
- El self.cards contendria solo los datos de las cartas que estan en la partida
- deck y discard_pile, guardarian las ID de las cartas que se encuentran en deck o discard_pile
esto haria mas facil cuando no quedan cartas en deck, hacer un shufle de discard_pile y ponerlo como deck

La verdad que se me hace dificil verlo con querys a pony.orm, porque los parametros de las query,
osea las cartas que no se pueden sacar o si en cada caso serian variables y me cuesta visualizarlo en general

2023-10-11 01:17 UTC, TroianoSan commented on app/game/models.py
> +        random.shuffle(mazoMezclaInicial)
La logica pesada es la reparticion de cartas en la vida real, como esta en las reglas del juego

https://famaf.aulavirtual.unc.edu.ar/pluginfile.php/27371/mod_resource/content/1/Reglas%20del%20Juego_%20La%20Cosa.pdf

A mi me parecio mas sencillo verlo como si lo estuviera repartiendo en la vida real.

2023-10-11 14:09 UTC, Jety16 reviewed
Revision
@lauta-rodriguez

2023-10-11 14:09 UTC, Jety16 commented on app/game/models.py
> +    deck = Optional(str, nullable=True)
prohibidas == no están en el deck

Dejalo asi como lo hiciste. no tenemos tiempo ya para ponerse refinados.
Lo que si vas a tener que cambiar en los jugadores la logica de las cartas.
actualmente las hands guardan cartas, si hacemos que self.cards mantenga las cartas de toda la partida, hay rebundancia extrema de datos ya que los jugadores van a tener que tener una relacion con las cartas. 
Mejor si usas la misma logica del discard_pile y el deck de las ids.

Despues pensá como hacerlo sin usar listas de json (esto genera mucha baja de performance para querys largas) sql no es capaz de trabajar con listas, si fuese sqlite todo gud. 
si no encontras otra forma ya fue. 
Mientras funcione todo ok. Despues si tenemos tiempo lo refinamos

@lauta-rodriguez  que opinas?

2023-10-11 14:09 UTC, Jety16 commented on app/game/models.py
> +    def initial_repartition_of_cards(self):
ok lo de infectado

2023-10-11 14:09 UTC, Jety16 commented on app/game/models.py
> +    def initial_repartition_of_cards(self):
Lo otro es la funcion que pisaste en el view

        # Give cards to users
        game.give_cards_to_users()
        
     `
    def give_cards_to_users(self):
        player_it = random.randint(0, len(self.players) - 1)
        self.the_thing = player_it

        # We gonna give cards to each player 4 cards then 4 cards...
        # dont have time to think about a better approach.
        # i'm gonna upgrade the algorithm of this function later

        for i, player in enumerate(self.players):
            cards = self.cards.random(CARDS_PER_PERSON)
            if i == player_it:
                cards = list(cards)
                cards[0] = self.cards.select(number=0).first()

            self.cards.remove(cards)

            # This is needed bcs QueryResults are buggy and not documented...
            # https://github.com/ponyorm/pony/issues/369
            cards = list(cards)

            # Remove this after demo
            try:
                torch = ModelBase().get_first_record_by_value(Card,
                    name='Lanzallamas', number=self.max_players)
                if torch is not None:
                    cards[1] = torch
            except Exception:
                pass

            player.add_cards(cards)
`

2023-10-11 14:09 UTC, Jety16 commented on app/game/models.py
> +        random.shuffle(mazoMezclaInicial)
ok, respondiendo lo primero si, usas filter.
lo otro, está bien pero me parece agregar complicacion al código pero weno si funciona ya era

2023-10-11 14:09 UTC, Jety16 commented on app/game/models.py
> +                mazoMezclaInicial.pop(0)
no hay que pasar explicitamente la funcionalidad de la vida real.
por ejemplo si tenes un programa que es un ecommerce no simulas la transferencia de un billete de 10 un billete de 20 sino que pasas directamente el monto.
Abstraerse mas y evitar perdida de rendimiento

2023-10-11 14:10 UTC, Jety16 commented
Solucionar conflictos

2023-10-11 20:56 UTC, TroianoSan commented on app/game/models.py
> +                mazoMezclaInicial.pop(0)
tenes razon

2023-10-11 21:13 UTC, TroianoSan commented on app/game/models.py
> +    def initial_repartition_of_cards(self):
Es verdad, pense que me tocaba a mi esa funcionalidad. Tenia asignado un ticket general 'Repartir cartas inicio partida' +  y habia un subticket que era a jugadores(que lo tenes vos hecho) y como tenia el ticket repartir cartas al inicio de partida habia hecho todo. Entonces la funcion initial_repartition_of_cards no se deberia usar, y en el views se deberia llamar

game.assign_cards_to_game()
game.assign_cards_to_users()

2023-10-12 03:16 UTC, TroianoSan commented on app/game/models.py
> +    deck = Optional(str, nullable=True)
me parecio dificil ver un esquema mental de como seria la implementacion de ese approach, pero pude verlo, y si, es mucho mejor tu approach, con las query a pony orm/ahorros de memoria en los campos, mas adelante si hay tiempo hacemos el cambio, si bien me costo verlo, ahora no me parece 'dificil' de implementar

2023-10-12 13:18 UTC, Jety16 commented
solucionar conflictos

2023-10-13 14:36 UTC, Jety16 requested changes
faltan hacer correciones

2023-10-13 14:36 UTC, Jety16 commented on app/game/models.py
> +        commit()
commit after db_session.
quitar

2023-10-14 15:19 UTC, Jety16 approved these changes

2023-10-14 15:20 UTC, merged